<?php

/**
 * PluginCEP_BrazilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCEP_BrazilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCEP_BrazilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCEP_Brazil');
    }
}